<a href="https://colab.research.google.com/github/sudemasali/AI-Bootcamp-Projects-/blob/main/feature_engineering_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ÖZNİTELİK MÜHENDİSLİĞİ

In [ ]:
#1.mevcut sütunlardan yeni özellikler üret(feature extraction)
#2.hedef değişken ile öznitelik arasındaki korelasyonları incele
#3.mutlak korelasyon değeri yüksek olan öznitelikleri seç

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("oznitelik_muhendisligi_pratik.csv")
df.head()

,yas,deneyim_yili,aylik_harcama,uyelik_suresi_ay,sehir,performans_puani
0,24,1,3200,6,Ankara,58
1,27,3,4100,12,Istanbul,64
2,31,5,5200,18,Izmir,71
3,35,8,6100,24,Ankara,79
4,29,4,4700,15,Bursa,68

In [4]:
#mevcut sütundan yeni özellikler üret
df["deneyim_orani"] = df["deneyim_yili"] / df["yas"]
df["yillik_harcama_tahmini"] = df["aylik_harcama"]*12
df

,yas,deneyim_yili,aylik_harcama,uyelik_suresi_ay,sehir,performans_puani,deneyim_orani,yillik_harcama_tahmini
0,24,1,3200,6,Ankara,58,0.041667,38400
1,27,3,4100,12,Istanbul,64,0.111111,49200
2,31,5,5200,18,Izmir,71,0.161290,62400
3,35,8,6100,24,Ankara,79,0.228571,73200
4,29,4,4700,15,Bursa,68,0.137931,56400
5,42,14,7600,40,Istanbul,88,0.333333,91200
6,38,11,6900,32,Izmir,84,0.289474,82800
7,26,2,3600,8,Ankara,61,0.076923,43200
8,33,7,5900,20,Bursa,75,0.212121,70800
9,45,16,8100,46,Istanbul,91,0.355556,97200
10,30,5,5000,16,Izmir,70,0.166667,60000
11,28,3,4300,10,Ankara,65,0.107143,51600

In [5]:
#hedef değişken ile öznitelik arasındaki korelasyonları incele
sayisal_df = df.drop("sehir", axis=1)
korelasyonlar = sayisal_df.corr()["performans_puani"].sort_values(ascending=False)
korelasyonlar

performans_puani          1.000000
yillik_harcama_tahmini    0.998033
aylik_harcama             0.998033
deneyim_orani             0.997640
yas                       0.991814
deneyim_yili              0.985984
uyelik_suresi_ay          0.982116
Name: performans_puani, dtype: float64

In [6]:
# mutlak korelasyon değeri yüksek olan öznitelikleri seç
secilen_oznitelikler = korelasyonlar[abs(korelasyonlar) > 0.995].index.tolist()
secilen_oznitelikler.remove("performans_puani")
secilen_oznitelikler

['yillik_harcama_tahmini', 'aylik_harcama', 'deneyim_orani']